/* ParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
/** MA imports */

import parserElements.*;
import parserExceptions.*;
import compilerElements.*;
import java.util.Map;
import java.util.HashMap;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

/** Token Manager. */
@SuppressWarnings("unused")public class ParserTokenManager implements ParserConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x6000000L) != 0L)
            return 14;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         return jjStartNfaWithStates_0(0, 26, 14);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 40:
         return jjStopAtPos(0, 40);
      case 41:
         return jjStopAtPos(0, 41);
      case 42:
         return jjStopAtPos(0, 38);
      case 43:
         return jjStopAtPos(0, 36);
      case 44:
         return jjStopAtPos(0, 29);
      case 45:
         jjmatchedKind = 37;
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 47:
         return jjStopAtPos(0, 39);
      case 58:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 59:
         jjmatchedKind = 30;
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 60:
         jjmatchedKind = 20;
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 61:
         jjmatchedKind = 28;
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 62:
         jjmatchedKind = 22;
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 126:
         return jjStartNfaWithStates_0(0, 25, 14);
      default :
         return jjMoveNfa_0(3, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(1, 23);
         break;
      case 59:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(1, 7);
         break;
      case 61:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(1, 16);
         else if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(1, 17);
         else if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(1, 19);
         else if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(1, 21);
         break;
      case 62:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(1, 15);
         break;
      case 124:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(1, 24);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 120;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 35)
                        kind = 35;
                     { jjCheckNAdd(22); }
                  }
                  else if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  if (curChar == 61)
                     kind = 18;
                  break;
               case 16:
                  if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 34)
                     kind = 34;
                  jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  { jjCheckNAdd(22); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 34)
                        kind = 34;
                     { jjCheckNAdd(21); }
                  }
                  else if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 14;
                  if (curChar == 73)
                     { jjCheckNAddStates(0, 3); }
                  else if (curChar == 69)
                     { jjAddStates(4, 7); }
                  else if (curChar == 70)
                     { jjAddStates(8, 11); }
                  else if (curChar == 84)
                     { jjAddStates(12, 15); }
                  else if (curChar == 101)
                     { jjAddStates(16, 17); }
                  else if (curChar == 116)
                     { jjAddStates(18, 19); }
                  else if (curChar == 105)
                     { jjCheckNAddTwoStates(73, 74); }
                  else if (curChar == 102)
                     { jjAddStates(20, 21); }
                  else if (curChar == 81)
                     { jjAddStates(22, 23); }
                  else if (curChar == 67)
                     { jjAddStates(24, 27); }
                  else if (curChar == 99)
                     { jjAddStates(28, 29); }
                  else if (curChar == 78)
                     { jjAddStates(30, 31); }
                  else if (curChar == 87)
                     { jjAddStates(32, 33); }
                  else if (curChar == 68)
                     { jjCheckNAddTwoStates(28, 12); }
                  else if (curChar == 76)
                     { jjAddStates(34, 35); }
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 18;
                  else if (curChar == 100)
                     { jjCheckNAdd(12); }
                  else if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 10;
                  else if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 5;
                  else if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 0:
                  if (curChar == 116 && kind > 5)
                     kind = 5;
                  break;
               case 1:
               case 63:
                  if (curChar == 105)
                     { jjCheckNAdd(0); }
                  break;
               case 2:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 4:
                  if (curChar == 119 && kind > 9)
                     kind = 9;
                  break;
               case 5:
               case 40:
                  if (curChar == 101)
                     { jjCheckNAdd(4); }
                  break;
               case 6:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 101 && kind > 13)
                     kind = 13;
                  break;
               case 8:
               case 34:
                  if (curChar == 108)
                     { jjCheckNAdd(7); }
                  break;
               case 9:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 111 && kind > 14)
                     kind = 14;
                  break;
               case 13:
                  if (curChar == 100)
                     { jjCheckNAdd(12); }
                  break;
               case 15:
                  if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 17:
                  if (curChar == 116 && kind > 27)
                     kind = 27;
                  break;
               case 18:
               case 26:
                  if (curChar == 101)
                     { jjCheckNAdd(17); }
                  break;
               case 19:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
               case 21:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 34)
                     kind = 34;
                  { jjCheckNAdd(21); }
                  break;
               case 23:
                  if (curChar == 76)
                     { jjAddStates(34, 35); }
                  break;
               case 24:
                  if (curChar == 84 && kind > 27)
                     kind = 27;
                  break;
               case 25:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 27:
                  if (curChar == 68)
                     { jjCheckNAddTwoStates(28, 12); }
                  break;
               case 28:
                  if (curChar == 79 && kind > 14)
                     kind = 14;
                  break;
               case 29:
                  if (curChar == 87)
                     { jjAddStates(32, 33); }
                  break;
               case 30:
                  if (curChar == 69 && kind > 13)
                     kind = 13;
                  break;
               case 31:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 35:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 78)
                     { jjAddStates(30, 31); }
                  break;
               case 38:
                  if (curChar == 87 && kind > 9)
                     kind = 9;
                  break;
               case 39:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 41:
                  if (curChar == 99)
                     { jjAddStates(28, 29); }
                  break;
               case 42:
                  if (curChar == 115 && kind > 6)
                     kind = 6;
                  break;
               case 43:
               case 51:
                  if (curChar == 108)
                     { jjCheckNAdd(42); }
                  break;
               case 44:
                  if (curChar == 114 && kind > 6)
                     kind = 6;
                  break;
               case 45:
               case 56:
                  if (curChar == 97)
                     { jjCheckNAdd(44); }
                  break;
               case 46:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 67)
                     { jjAddStates(24, 27); }
                  break;
               case 49:
                  if (curChar == 83 && kind > 6)
                     kind = 6;
                  break;
               case 50:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 52:
                  if (curChar == 82 && kind > 6)
                     kind = 6;
                  break;
               case 53:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 57:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if (curChar == 81)
                     { jjAddStates(22, 23); }
                  break;
               case 60:
                  if (curChar == 84 && kind > 5)
                     kind = 5;
                  break;
               case 61:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 64:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if (curChar == 102)
                     { jjAddStates(20, 21); }
                  break;
               case 66:
                  if (curChar == 110 && kind > 8)
                     kind = 8;
                  break;
               case 67:
               case 101:
                  if (curChar == 117)
                     { jjCheckNAdd(66); }
                  break;
               case 68:
                  if (curChar == 101 && kind > 33)
                     kind = 33;
                  break;
               case 69:
               case 105:
                  if (curChar == 115)
                     { jjCheckNAdd(68); }
                  break;
               case 70:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 105)
                     { jjCheckNAddTwoStates(73, 74); }
                  break;
               case 73:
                  if (curChar == 102 && kind > 10)
                     kind = 10;
                  break;
               case 74:
                  if (curChar == 110 && kind > 31)
                     kind = 31;
                  break;
               case 75:
                  if (curChar == 116)
                     { jjAddStates(18, 19); }
                  break;
               case 76:
                  if (curChar == 110 && kind > 11)
                     kind = 11;
                  break;
               case 77:
               case 91:
                  if (curChar == 101)
                     { jjCheckNAdd(76); }
                  break;
               case 78:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
               case 96:
                  if (curChar == 117)
                     { jjCheckNAdd(68); }
                  break;
               case 80:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 101)
                     { jjAddStates(16, 17); }
                  break;
               case 82:
                  if (curChar == 101 && kind > 12)
                     kind = 12;
                  break;
               case 83:
               case 112:
                  if (curChar == 115)
                     { jjCheckNAdd(82); }
                  break;
               case 84:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 100 && kind > 32)
                     kind = 32;
                  break;
               case 86:
               case 116:
                  if (curChar == 110)
                     { jjCheckNAdd(85); }
                  break;
               case 87:
                  if (curChar == 84)
                     { jjAddStates(12, 15); }
                  break;
               case 88:
                  if (curChar == 78 && kind > 11)
                     kind = 11;
                  break;
               case 89:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 92:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 69 && kind > 33)
                     kind = 33;
                  break;
               case 94:
                  if (curChar == 85)
                     { jjCheckNAdd(93); }
                  break;
               case 95:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 97:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 70)
                     { jjAddStates(8, 11); }
                  break;
               case 99:
                  if (curChar == 78 && kind > 8)
                     kind = 8;
                  break;
               case 100:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 102:
                  if (curChar == 83)
                     { jjCheckNAdd(93); }
                  break;
               case 103:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 106:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 69)
                     { jjAddStates(4, 7); }
                  break;
               case 109:
                  if (curChar == 69 && kind > 12)
                     kind = 12;
                  break;
               case 110:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 113:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 68 && kind > 32)
                     kind = 32;
                  break;
               case 115:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 117:
                  if (curChar == 73)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 118:
                  if (curChar == 70 && kind > 10)
                     kind = 10;
                  break;
               case 119:
                  if (curChar == 78 && kind > 31)
                     kind = 31;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 120 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   118, 73, 119, 74, 111, 113, 115, 116, 100, 101, 104, 107, 90, 92, 95, 97, 
   84, 86, 78, 80, 67, 71, 62, 64, 50, 51, 55, 58, 43, 47, 39, 40, 
   33, 36, 25, 26, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\73\73", null, null, null, null, null, 
null, null, "\55\76", "\72\75", "\75\75", null, "\74\75", "\74", "\76\75", "\76", 
"\46\46", "\174\174", "\176", "\41", null, "\75", "\54", "\73", null, null, null, null, 
null, "\53", "\55", "\52", "\57", "\50", "\51", };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public ParserTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public ParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 120; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  static public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3ffffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[120];
    static private final int[] jjstateSet = new int[2 * 120];

    
    static protected char curChar;
}
