/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int QUIT = 4;
  /** RegularExpression Id. */
  int FINAL = 5;
  /** RegularExpression Id. */
  int FUN = 6;
  /** RegularExpression Id. */
  int NEW = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int THEN = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int POINT = 13;
  /** RegularExpression Id. */
  int ASSIGN = 14;
  /** RegularExpression Id. */
  int MATCH = 15;
  /** RegularExpression Id. */
  int NOT_MATCH = 16;
  /** RegularExpression Id. */
  int LESS_EQUAL = 17;
  /** RegularExpression Id. */
  int LESS = 18;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 19;
  /** RegularExpression Id. */
  int GREATER = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int NOT = 23;
  /** RegularExpression Id. */
  int DEASSIGN = 24;
  /** RegularExpression Id. */
  int LET = 25;
  /** RegularExpression Id. */
  int EQUAL = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int SEMICOLON = 28;
  /** RegularExpression Id. */
  int IN = 29;
  /** RegularExpression Id. */
  int END = 30;
  /** RegularExpression Id. */
  int Bool = 31;
  /** RegularExpression Id. */
  int Id = 32;
  /** RegularExpression Id. */
  int Num = 33;
  /** RegularExpression Id. */
  int PLUS = 34;
  /** RegularExpression Id. */
  int MINUS = 35;
  /** RegularExpression Id. */
  int TIMES = 36;
  /** RegularExpression Id. */
  int DIV = 37;
  /** RegularExpression Id. */
  int LPAR = 38;
  /** RegularExpression Id. */
  int RPAR = 39;
  /** RegularExpression Id. */
  int EL = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<QUIT>",
    "\";;\"",
    "<FUN>",
    "<NEW>",
    "<IF>",
    "<THEN>",
    "<ELSE>",
    "<WHILE>",
    "<DO>",
    "\"->\"",
    "\":=\"",
    "\"==\"",
    "<NOT_MATCH>",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\"!\"",
    "<LET>",
    "\"=\"",
    "\",\"",
    "\";\"",
    "<IN>",
    "<END>",
    "<Bool>",
    "<Id>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
  };

}
