/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINTLN = 5;
  /** RegularExpression Id. */
  int QUIT = 6;
  /** RegularExpression Id. */
  int CLEAR = 7;
  /** RegularExpression Id. */
  int FINAL = 8;
  /** RegularExpression Id. */
  int STRUCT = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int REF = 13;
  /** RegularExpression Id. */
  int FUN = 14;
  /** RegularExpression Id. */
  int NEW = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int APPLY = 21;
  /** RegularExpression Id. */
  int ASSIGN = 22;
  /** RegularExpression Id. */
  int MATCH = 23;
  /** RegularExpression Id. */
  int NOT_MATCH = 24;
  /** RegularExpression Id. */
  int LESS_EQUAL = 25;
  /** RegularExpression Id. */
  int LESS = 26;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 27;
  /** RegularExpression Id. */
  int GREATER = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int LCBRACKET = 32;
  /** RegularExpression Id. */
  int RCBRACKET = 33;
  /** RegularExpression Id. */
  int DOT = 34;
  /** RegularExpression Id. */
  int QUOTE = 35;
  /** RegularExpression Id. */
  int DEASSIGN = 36;
  /** RegularExpression Id. */
  int LET = 37;
  /** RegularExpression Id. */
  int EQUAL = 38;
  /** RegularExpression Id. */
  int COMMA = 39;
  /** RegularExpression Id. */
  int COLON = 40;
  /** RegularExpression Id. */
  int SEMICOLON = 41;
  /** RegularExpression Id. */
  int IN = 42;
  /** RegularExpression Id. */
  int END = 43;
  /** RegularExpression Id. */
  int Bool = 44;
  /** RegularExpression Id. */
  int Id = 45;
  /** RegularExpression Id. */
  int Num = 46;
  /** RegularExpression Id. */
  int PLUS = 47;
  /** RegularExpression Id. */
  int MINUS = 48;
  /** RegularExpression Id. */
  int TIMES = 49;
  /** RegularExpression Id. */
  int DIV = 50;
  /** RegularExpression Id. */
  int LPAR = 51;
  /** RegularExpression Id. */
  int RPAR = 52;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<PRINTLN>",
    "<QUIT>",
    "<CLEAR>",
    "\";;\"",
    "<STRUCT>",
    "<STRING>",
    "<INT>",
    "<BOOL>",
    "<REF>",
    "<FUN>",
    "<NEW>",
    "<IF>",
    "<THEN>",
    "<ELSE>",
    "<WHILE>",
    "<DO>",
    "\"->\"",
    "\":=\"",
    "\"==\"",
    "<NOT_MATCH>",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"\\\"\"",
    "\"!\"",
    "<LET>",
    "\"=\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "<IN>",
    "<END>",
    "<Bool>",
    "<Id>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
